-- Structure de la table 'articles'

create table public.articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  title text not null,
  excerpt text,
  quote_text text not null,
  author text not null,
  category text,
  read_time text default '6 min',
  image_url text,
  type text default 'analysis',
  content jsonb not null
);

-- Active la sécurité (RLS)
alter table public.articles enable row level security;

-- Créer une politique pour permettre la lecture à tout le monde
create policy "Enable read access for all users"
on public.articles for select
to public
using (true);

-- Créer une politique pour permettre l'insertion (si tu utilises l'API sans authentification utilisateur, enable 'anon' key inserts, sinon restreindre aux utilisateurs authentifiés)
-- ATTENTION : Pour le dev, on permet l'insert public pour tester. En prod, sécuriser.
create policy "Enable insert for all users"
on public.articles for insert
to public
with check (true);
